[package]
name = "ryuk-lispcompiler"
version = "0.1.0"
authors = ["Kyle Edwards <kyleedwardsny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ryuk-lisptypes = { path = "../lisptypes" }
